export const WAITING_TO_JOIN = 'join'
export const IN_LOBBY = 'lobby'
export const DISPLAYING_QUESTION = 'question'
export const DISPLAYING_LEADERBOARD = 'leaderboard'
export const DISPLAYING_WINNER = 'winner'
